// Generated by CoffeeScript 1.3.3
(function() {
  var $, callback;

  $ = jQuery;

  callback = function(data) {
    return alert(data);
  };

  $.get('stories.json', null, callback, 'json');

}).call(this);
