// Generated by CoffeeScript 1.3.3
var $, callback, sortElements, trendingSortElements;

$ = jQuery;

callback = function(data) {
  $('body').append('<ol id="list"></ol>');
  return $(data).each(function(i, element) {
    var a, li;
    li = $('<li />').attr({
      'posted_at': element.posted_at,
      'points': element.points
    });
    a = $('<a />');
    a.attr('href', element.link);
    a.text(element.title);
    li.append(a);
    li.append('<span class="grey">' + element.points + ' 10 minutes ago</span>');
    return $('#list').append(li);
  });
};

$.get('stories.json', null, callback, 'json');

sortElements = function(sortby) {
  var sorted;
  sorted = $('#list li').sort(function(a, b) {
    var aval, bval;
    aval = parseInt($(a).attr(sortby));
    bval = parseInt($(b).attr(sortby));
    if (aval === bval) {
      return 0;
    }
    if (aval < bval) {
      return -1;
    }
    if (aval > bval) {
      return 1;
    }
  });
  return $('#list').empty().append(sorted);
};

/*
	trending function for extra credit
	velocity = distance / time
	... so ...
	trending = points / time
*/


trendingSortElements = function() {
  var sorted;
  sorted = $('#list li').sort(function(a, b) {
    var aVelocity, bVelocity;
    aVelocity = parseInt($(a).attr('points')) / parseInt($(a).attr('posted_at'));
    bVelocity = parseInt($(b).attr('points')) / parseInt($(b).attr('posted_at'));
    if (aVelocity === bVelocity) {
      return 0;
    }
    if (aVelocity < bVelocity) {
      return -1;
    }
    if (aVelocity > bVelocity) {
      return 1;
    }
  });
  return $('#list').empty().append(sorted);
};
